config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

post '/issues/:id/send_rating_mail', :to => 'ratings#send_rating_mail'
get '/rating/:key', :to => 'ratings#set_rating'
get 'projects/:project_id/rating/report', :to => 'ratings#report'

app/models/rating.rb
class Rating < ActiveRecord::Base
  unloadable
  belongs_to :issue

   def self.gen_uniq_key
     o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
     (0...50).map { o[rand(o.length)] }.join
   end
end

app/controllers/ratings_controller.rb
#!/bin/env ruby
# encoding: utf-8
class RatingsController < ApplicationController
  def send_rating_mail
    @issue = Issue.find params[:id]

    if !@issue.rating.blank?
      flash[:error] = "Оценка по задаче уже выставлена и не может быть запрошена повторно"
    elsif @issue.ratings.any?&&(@issue.ratings.first.created_on+3)>Date.current
      flash[:error] = "Оценка по задаче запрашивалась менее 3х дней назад"
    elsif @issue.client_mail
      @issue.gen_ratings
      begin
        Mailer.get_rating(@issue).deliver
        flash[:notice] = 'Запрос оценки успешно направлен заказчику'
      rescue
        flash[:error] = 'Во время отправки запроса оценки произошел сбой, проверьте корректность почтового адреса клиента и попробуйте еще раз'
        @issue.ratings.each {|r| r.destroy}
      end
    else
      flash[:error] = 'Либо Исполнитель должен быть клиентом, либо в поле Клиент - значение в формате "...<<email>>"'
    end
    redirect_to @issue
  end

  def set_rating
    if (rating = Rating.find_by_key(params[:key]))
      @issue = rating.issue
      @issue.rating = rating.rating
      @issue.ratings.each {|r| r.destroy}
      render 'thanks_for_rating'
    else
      render 'not_found'
    end
  end

  def report
    @project = Project.find(params['project_id'])
    date_from = params[:date_from]
    date_to = params[:date_to]
    template = 'report_rating'

    pr={}

    pr.merge! 'issue' => :master
    @issues = @project.issues.where("due_date between '#{date_from}' and '#{date_to}'").order(:id).all


    generate_rtf_by_template pr, "#{template}.rtf", "#{template}-#{@project.identifier}.rtf"
  end


  private

  TEMPLATESPATH = "#{PLUGIN_PATH}/templates/"

  def generate_rtf_by_template params, file_name_input, file_name_output
    file_name_input  = TEMPLATESPATH + file_name_input

    # Загружаем шаблон
    begin
      template  = File.open(file_name_input,"r") {|file|file.read}
    rescue BlogDataNotFound
      STDERR.puts "Файл #{file_name_input} не найден"
    rescue Exception => exc
      STDERR.puts " Общая ошибка загрузки #{file_name_input}: #{exc.message}"
    end

    temp = [[],[],[],[],[]]
    u    = ['','','','','']
    a = template.split(/(<%start\(\w+\)%>|<%end%>)/)
    k = 0
    del_par = false
    a.map do |s|
      if s =~ /<%start\((\w+)\)%>/
        k = k+1
        u[k] = $1
        temp[k] = []
        del_par = true
      elsif s =~ /<%end%>/
        temp[k-1] << {u[k].to_s => temp[k]}
        k=k-1
        del_par = true
      else
        if del_par
          s.sub!('\par ',' ')
        end
        temp[k] << s
        del_par = false
      end
    end
    a = temp[0]

    @output = ''
    replace_rtf a, params
    @output = @output.recode_for_rtf

    send_data @output,
              :filename => file_name_output,
              :type => 'application/msword',
              :disposition => 'attachment'
  end

  def replace_rtf(ar, params)
    ar.each do |s|
      if s.class == String
        t=String.new(s)
        t.gsub!(/<%(\w+)%>/)          { params[$1].to_s.gsub(/\n/,'\\par ') }
        t.gsub!(/<%(\w+)\.(\w+)%>/)   { self.instance_variable_get("@#{$1}").send($2).to_s.gsub(/\n/){'\\par '} }
        t.gsub!(/<%(\w+)\[(\w+)\]%>/) { self.instance_variable_get("@#{$1}").call(self.instance_variable_get("@#{$2}")) }
        @output << t
      else
        s.each do |list, sub_a|
          if params[list] == :detail
            self.instance_variable_get("@#{list}_detail").call
          end

          self.instance_variable_get("@#{list}s").each do |item|
            self.instance_variable_set("@#{list}", item)
            replace_rtf sub_a, params
          end
        end
      end
    end
  end


end

app/helpers/homnet_settings_helper.rb
# frozen_string_literal: true

module HomnetSettingsHelper
  def plugin_setting_select_from_collection(setting, choices, options = {})
    setting_label(setting, options).html_safe +
      select_tag("settings[#{setting}]",
                 options_from_collection_for_select(choices, 'id', 'name', Setting.send("plugin_#{@plugin.id}")[setting.to_s]),
                 options).html_safe
  end

  def plugin_setting_multiselect(setting, choices, options = {})
    setting_values = Setting.send("plugin_#{@plugin.id}")[setting]
    setting_values = [] unless setting_values.is_a?(Array)

    content_tag('label', l(options[:label] || "setting_#{setting}")) +
      hidden_field_tag("settings[#{setting}][]", '').html_safe +
      choices.collect do |choice|
        text, value = (choice.is_a?(Array) ? choice : [choice, choice])
        content_tag(
          'p',
          content_tag(
            'label',
            check_box_tag(
              "settings[#{setting}][]",
              value,
              setting_values.include?(value),
              id: nil
            ) + text.to_s,
            class: (options[:inline] ? 'inline' : 'block')
          )
        )
      end.join.html_safe
  end

  def plugin_setting_text_field(setting, options = {})
    setting_label(setting, options).html_safe +
      text_field_tag("settings[#{setting}]", Setting.send("plugin_#{@plugin.id}")[setting], options).html_safe
  end

  def plugin_setting_check_box(setting, options = {})
    setting_label(setting, options).html_safe +
      check_box_tag("settings[#{setting}]", 1, Setting.send("plugin_#{@plugin.id}")[setting], options).html_safe
  end
end

app/views/issues/_view_issues_new_top.erb
<%
  settings = Setting.plugin_homnet
  project_ids = settings['project_ids'].to_a
  if @issue.project_id.to_s.in?(project_ids) &&
      @issue.author.roles.ids.include?(settings['homnet_hd_role'].to_i)
    cf = ProjectCustomField.find_by(id: Setting.plugin_homnet['homnet_hd_assign_field'])
    @issue.assigned_to_id = @issue.project.custom_value_for(cf)&.value
  end
%>

app/views/issues/show/_details_bottom.erb
<% if @issue.status.name == 'Подписание ЛУРВ' %>
  <%= button_to "Запросить оценку", "#{issue_path(@issue)}/send_rating_mail", :class => 'button', :method => 'post' %>
<% end %>

app/views/projects/show/_right.erb
<%= form_tag("#{@project.id}/rating/report", :method => "get") do %>
  <%= hidden_field_tag(:project_id, @project.id) %>
  <fieldset class="box tabular">
    <legend>Отчет по оценкам за период</legend>
    C
    <%= text_field_tag(:date_from, nil, :size => 10) %>
    <%= calendar_for('date_from')%>
    по
    <%= text_field_tag(:date_to, nil, :size => 10) %>
    <%= calendar_for('date_to')%>
    <%= submit_tag("Выполнить") %>
  </fieldset>
<% end %>

app/views/ratings/not_found.erb
Не найдена оценка

app/views/ratings/thanks_for_rating.erb
Спасибо за выставленную оценку

app/views/settings/_homnet.html.haml
- plugin_settings_tag = "plugin_#{@plugin.id}"
- plugin_settings = Setting.send(plugin_settings_tag)

%fieldset.settings
  .splitcontentleft
    %fieldset.settings
      //%p= plugin_setting_select_from_collection :homnet_hd_project, Project.all, blank: :label_none
      //#%p= plugin_setting_select_from_collection :homnet_hd_group, Group.all, blank: :label_none
      //#%p= plugin_setting_select_from_collection :homnet_hd_user, User.all, blank: :label_none


      %p= plugin_setting_select_from_collection :homnet_hd_role, Role.all, blank: :label_none
      %p= plugin_setting_select_from_collection :homnet_hd_assign_field, ProjectCustomField.where(field_format: 'user').all, blank: :label_none

      %p= plugin_setting_select_from_collection :homnet_hd_accept_field, IssueCustomField.where(field_format: 'bool').all, blank: :label_none
      %p= plugin_setting_select_from_collection :homnet_hd_month_field, IssueCustomField.all, blank: :label_none


  .splitcontentright
    - projects = Project.all
    - setting = 'project_ids'
    - project_ids = plugin_settings[setting].to_a
    %fieldset.box#homnet_project_ids
      %legend Клиентские проекты
      = render_project_nested_lists(projects) do |p|
        %label.no-css(style="margin-left:0px" )
          = check_box_tag("settings[project_ids][]", p.id, project_ids.include?(p.id.to_s), :id => nil)
          = h(p)
      = hidden_field_tag("settings[project_ids][]", '', :id => nil)
      %p= check_all_links 'homnet_project_ids'